### ISSUE TITLE
How to change images?

### ISSUE THREAD

**Issue by raysefo** [ZeroOneStudio/kenburnsy#3]
Hello @romanenko,

Is there a way to change images?

Best Regards.

**Comment by raysefo** [comment]
Would you please help me?

**Comment by raysefo** [comment]
any help?

**Comment by romanenko** [comment]
Hello, @raysefo. Sorry for the late answer: was very busy, meeting deadlines on current projects.

Have you resolved your issue? You wanted to change images dynamically?

**Comment by raysefo** [comment]
hi @romanenko , I think images are in the js file.

**Comment by romanenko** [comment]
No, they are not. Here, I made a tiny fiddle with some random images from Unsplash: https://jsfiddle.net/Lyzufen4/

**Comment by raysefo** [comment]
OK thank you @romanenko
